version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: email-agent-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: email_agent
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: email-agent-backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/email_agent
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      NODE_ENV: production
      STACK_PROJECT_ID: ${STACK_PROJECT_ID}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      # Mount .env file if it exists
      - ./.env:/app/.env:ro

volumes:
  postgres_data: 