name = "chat-widget-agent"
# Proxy Worker that streams OpenAI completions
main = "src/worker-openai.ts"
compatibility_date = "2024-06-10"
compatibility_flags = ["nodejs_compat"]
[dev]
port = 3001 

[vars]
OPENAI_API_KEY = "your_key"