name: Trigger docs → OpenAI sync

on:
  push:
    branches: [master, rag]
    paths: ['rag/knowledge-base/**']     # run only when docs change
  workflow_dispatch:                # allow manual “Run workflow”

jobs:
  call-sync:
    uses: ./rag/.ci/sync-knowledge-base.yml
    secrets:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}